# Adding Environment Variables to the container in the Pod

apiVersion: v1
kind: Pod
metadata:
  name: my-flask-app
spec:
  containers:
  - name: my-flask-app
    image: ghcr.io/emmanuelogiji/cloudboosta-flask-app:0.2.0
    ports:
    - containerPort: 9900
    env:
    - name: LOG_LEVEL
      value: "DEBUG"
    - name: AUTHOR
      value: "Pod"

