resources:
  requests:
    memory: "25Mi"
    cpu: "250m"
  limits:
    memory: "50Mi"
    cpu: "500m"
volumeMounts:
  - name: config-volume
    mountPath: /app/templates/
envFrom:
  - configMapRef:
      name: flask-config
env:
  - name: AUTHOR
    valueFrom:
      secretKeyRef:
        name: flask-secret
        key: AUTHOR_NAME
startupProbe:
  httpGet:
    path: /author
    port: 9900
  failureThreshold: 30
  periodSeconds: 10
readinessProbe:
  tcpSocket:
    port: 9900
  initialDelaySeconds: 5
  periodSeconds: 10
livenessProbe:
  tcpSocket:
    port: 9900
  initialDelaySeconds: 15
  periodSeconds: 20