cat << EOF > secret-store-explicit.yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${AWS_REGION}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: access-key
            namespace: default
          secretAccessKeySecretRef:
            name: aws-credentials
            key: secret-key
            namespace: default
EOF
